#!/usr/bin/python2

import hooking
import os

domxml = hooking.read_domxml()

if hooking.tobool(os.environ.get('gpupassthrough')):

  hyperv = domxml.getElementsByTagName('hyperv')[0]
  smm = domxml.createElement('vendor_id')
  smm.setAttribute('state', 'on')
  smm.setAttribute('value', 'whatever')
  hyperv.appendChild(smm)

  features = domxml.getElementsByTagName('features')[0]
  kvm = domxml.createElement('kvm')
  hidden = domxml.createElement('hidden')
  hidden.setAttribute('state', 'on')
  kvm.appendChild(hidden)
  features.appendChild(kvm)


#  features = domxml.getElementsByTagName('features')[0]
  vmport = domxml.createElement('vmport')
  vmport.setAttribute('state', 'off')
  features.appendChild(vmport)

#  features = domxml.getElementsByTagName('features')[0]
  ioapic = domxml.createElement('ioapic')
  ioapic.setAttribute('driver', 'kvm')
  features.appendChild(ioapic)

  hostdev = domxml.getElementsByTagName('hostdev')[0]
  vbios = domxml.createElement('rom')
  vbios.setAttribute('file', 'xxxxx')
  hostdev.appendChild(vbios)

  hooking.write_domxml(domxml)
